apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testjava
  name: testjava
spec:
  ports:
  - port: 8585
    protocol: TCP
    targetPort: 8080
  selector:
    app: test
  type: NodePort
status:
  loadBalancer: {}
